name             'phpmyadmin'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures phpmyadmin'
long_description 'Installs/Configures phpmyadmin'
version          '0.1.0'

depends 'apt'
depends 'apache2', '~> 3.1.0'
depends 'mysql', '~> 6.0'
